### ISSUE TITLE
Unix build support

### ISSUE THREAD

**Issue by briantrice** [zero-motorcycle-community/browser-parse#2]
PowerShell is a very clumsy tool for this.

**Comment by keithxemi** [comment]
OK, this seems alright to me. Peaceful coexistence between OS's is possible with some grumbling on all sides.  I don't like PowerShell either but using Posix on Windows is beyond clumsy so I think we can maintain parallel build tools. It looks like that may cause some blank lines to come and go in the html but that's ok. Great if it gets more contributors, could be trouble if the structure needs big changes.
